ALTER TABLE ESTOQUE
DROP CONSTRAINT ESTOQUE_PKEY;

ALTER TABLE ESTOQUE
DROP CONSTRAINT IF EXISTS FK_PRODUTO;

ALTER TABLE ESTOQUE
ADD COLUMN ID SERIAL PRIMARY KEY;

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID);

ALTER TABLE MOV_ESTOQUE
ALTER COLUMN PRECO_FRETE DROP NOT NULL;
