ALTER TABLE ESTOQUE
DROP CONSTRAINT IF EXISTS ESTOQUE_PKEY;

ALTER TABLE ESTOQUE
DROP CONSTRAINT IF EXISTS FK_PRODUTO;

ALTER TABLE ESTOQUE
DROP COLUMN IF EXISTS ID;

ALTER TABLE ESTOQUE
ADD CONSTRAINT ESTOQUE_PKEY PRIMARY KEY (PRODUTO_ID);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID);

ALTER TABLE MOV_ESTOQUE
ALTER COLUMN PRECO_FRETE SET NOT NULL;
