CREATE TABLE USUARIO (
       ID      SERIAL    PRIMARY KEY,
       LOGIN   VARCHAR   NOT NULL,
       NOME    VARCHAR   NOT NULL,
       SENHA_H CHAR(64)  NOT NULL,
       SENHA_S BYTEA     NOT NULL
)
