CREATE TABLE ENDERECO (
    ID          SERIAL   PRIMARY KEY,
    CLIENTE_ID  SERIAL   NOT NULL,
    TIPO        SMALLINT NOT NULL,
    LOGRADOURO  VARCHAR  NOT NULL,
    NUMERO      VARCHAR  NOT NULL,
    COMPLEMENTO VARCHAR,
    BAIRRO      VARCHAR  NOT NULL,
    UF          VARCHAR  NOT NULL,
    CIDADE      VARCHAR  NOT NULL,
    CONSTRAINT FK_CLIENTE
    FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(ID)
)
