CREATE TABLE CLIENTE (
    ID        SERIAL   PRIMARY KEY,
    TIPO      SMALLINT NOT NULL  DEFAULT 0,
    NOME      VARCHAR  NOT NULL,
    PJ        BOOLEAN  NOT NULL  DEFAULT 'F',
    DOCTO     VARCHAR  NOT NULL,
    ATIVO     BOOLEAN  NOT NULL  DEFAULT 'T',
    BLOQUEADO BOOLEAN  NOT NULL  DEFAULT 'F'
)
