CREATE TABLE MOV_ESTOQUE (
       ID          SERIAL         PRIMARY KEY,
       PRODUTO_ID  SERIAL         NOT NULL,
       DOCTO       VARCHAR        NOT NULL,
       QUANTIDADE  NUMERIC(12,3)  NOT NULL,
       PRECO_FRETE NUMERIC(13,4),
       DATAHORA    TIMESTAMPTZ    NOT NULL,
       CONSTRAINT FK_PRODUTO
       FOREIGN KEY(PRODUTO_ID) REFERENCES PRODUTO(ID)
)
