CREATE TABLE PRODUTO (
    ID         SERIAL        PRIMARY KEY,
    DESCRICAO  VARCHAR       NOT NULL,
    UNIDSAIDA  VARCHAR       NOT NULL     DEFAULT 'UN',
    QTDESTOQUE NUMERIC(12,3) NOT NULL     DEFAULT 0.000,
    PRECOVENDA NUMERIC(13,4) NOT NULL
)
