CREATE TABLE LOGDB (
       ID        SERIAL    PRIMARY KEY,
       TABELA    VARCHAR   NOT NULL,
       USUARIO   VARCHAR   NOT NULL,
       OPERACAO  SMALLINT  NOT NULL,
       DATAHORA  TIMESTAMP NOT NULL,
       DESCRICAO VARCHAR
)
