CREATE TABLE ESTOQUE (
       ID            SERIAL        PRIMARY KEY,
       PRODUTO_ID    SERIAL        NOT NULL,
       QUANTIDADE    NUMERIC(12,3) NOT NULL,
       PRECOUNITARIO NUMERIC(13,4) NOT NULL DEFAULT 0.0000
);

ALTER TABLE PRODUTO
DROP COLUMN IF EXISTS QTDESTOQUE;

ALTER TABLE PRODUTO
DROP COLUMN IF EXISTS PRECOVENDA;
