ALTER TABLE USUARIO
DROP COLUMN IF EXISTS SENHA_HASH;

ALTER TABLE USUARIO
DROP COLUMN IF EXISTS EMAIL;

ALTER TABLE USUARIO
ADD COLUMN SENHA_H CHAR(64) NOT NULL;

ALTER TABLE USUARIO
ADD COLUMN SENHA_S BYTEA NOT NULL;

ALTER TABLE USUARIO
DROP CONSTRAINT IF EXISTS UQ_PRODUCT_LOGIN;
