ALTER TABLE USUARIO
DROP COLUMN IF EXISTS SENHA_H;

ALTER TABLE USUARIO
DROP COLUMN IF EXISTS SENHA_S;

ALTER TABLE USUARIO
ADD COLUMN EMAIL VARCHAR;

ALTER TABLE USUARIO
ADD COLUMN SENHA_HASH BYTEA NOT NULL;

ALTER TABLE USUARIO
ADD CONSTRAINT UQ_PRODUCT_LOGIN UNIQUE(LOGIN);
